### ISSUE TITLE
Missing qcom omx decoders?

### ISSUE THREAD

**Issue by andycris** [armani-dev/proprietary_vendor_xiaomi#5]
The following files are missing:
vendor/lib/libOmxAacDec.so
vendor/lib/libOmxAmrwbplusDec.so
vendor/lib/libOmxEvrcDec.so
vendor/lib/libOmxQcelp13Dec.so
vendor/lib/libOmxWmaDec.so

Why no hardware decoders?
Aren't we missing hardware decoding without these?

**Comment by fefifofum** [comment]
This is deprecated since https://github.com/armani-dev/android_device_xiaomi_armani/commit/c7c6a8e665d3587e7523c5715730b7b288f8eb13

There is no need of copying those blobs if they are not going to be used. Audio hardware decoder has been removed from media_codecs.xml. If you are comparing to motorola_msm8226, they also removed audio hardware from media_codecs.xml, they just forgot to remove the blobs.

https://github.com/CyanogenMod/android_device_motorola_msm8226-common/commit/f83bc0f33946f00b43f8ce8761d941fe2518810e
